lesson2
Sin93/geekshop-server pull request #2
Opened 2021-01-27 10:07 UTC by Sin93

Добрый день, извиняюсь, заработался и первый урок пропустил сдачу задания, по второму сделал всё кроме загрузки из json, я это умею делать (уже делал), но время поджимает, лучше третьим ДЗ займусь

2021-01-27 11:07 UTC, Sin93 commented
Добавил контакты из json

2021-01-27 14:13 UTC, Vokler commented
У вас не совсем верная структура репозитория, должно быть примерно вот так
https://github.com/Vokler/geekshop-486

2021-01-27 14:55 UTC, Sin93 commented
> У вас не совсем верная структура репозитория, должно быть примерно вот так
> https://github.com/Vokler/geekshop-486

Поправил как в примере, после мёрджа должно выправиться

2021-01-27 15:07 UTC, Sin93 commented
> У вас не совсем верная структура репозитория, должно быть примерно вот так
> https://github.com/Vokler/geekshop-486

2021-01-27 15:08 UTC, Sin93 commented
случайно не туда нажал

2021-01-27 15:17 UTC, Vokler requested changes

2021-01-27 15:17 UTC, Vokler commented on mainapp/templates/mainapp/products.html
> +				<a href="#"><img src="{% static 'img/product-11.jpg' %}" alt="">
У вас картинка за хардкожена, нужно поработать с изображениями.

2021-01-27 15:17 UTC, Vokler commented on mainapp/views.py
> +    context = {
Добавьте в context список продуктов, чтобы в шаблоне их вывести через цикл for, как мы это делали на 2ом уроке

2021-01-27 16:12 UTC, Sin93 commented
А, всё понял, добавить ссылки на продукты конкретные? сейчас докину

2021-01-27 17:04 UTC, Sin93 reviewed
Ссылка на картинку берётся из контекста, прицепил ссылки на каждый отдельный продукт

2021-01-28 11:02 UTC, Vokler commented
Да, примерно так. Только пернесите файлы `contacts.json` и `products.json` в mainapp/fixtures

2021-01-28 13:42 UTC, Sin93 commented
> Да, примерно так. Только пернесите файлы `contacts.json` и `products.json` в mainapp/fixtures

перенёс, + поправил views.py, чтоб формировался новый путь

2021-01-28 13:59 UTC, merged